version: 0.2

phases:
  pre_build:
    commands:
      - chmod +x $CODEBUILD_SRC_DIR/scripts/build
      - npm install -g yarn
      - yarn install


  build:
    commands:
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
